## 1.Проверить фичи для модели
## 2. Определить прогнозирующую переменную
## 3. Разбить датасет на тестовую и прогнозирующую 
## 4. Построить предиктивную модель
## 5. Оценить модель

In [1]:
import pandas as pd

In [2]:
df_diabets_data = pd.read_csv("pima-indians-diabetes.data")

In [3]:
df_diabets_data

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [4]:
df_diabets_data_mod = pd.read_csv("pima-indians-diabetes.data", header=None)

In [5]:
df_diabets_data_mod

      0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [6]:
with open("pima-indians-diabetes.names") as info:
    print(info.read())

1. Title: Pima Indians Diabetes Database

2. Sources:
   (a) Original owners: National Institute of Diabetes and Digestive and
                        Kidney Diseases
   (b) Donor of database: Vincent Sigillito (vgs@aplcen.apl.jhu.edu)
                          Research Center, RMI Group Leader
                          Applied Physics Laboratory
                          The Johns Hopkins University
                          Johns Hopkins Road
                          Laurel, MD 20707
                          (301) 953-6231
   (c) Date received: 9 May 1990

3. Past Usage:
    1. Smith,~J.~W., Everhart,~J.~E., Dickson,~W.~C., Knowler,~W.~C., \&
       Johannes,~R.~S. (1988). Using the ADAP learning algorithm to forecast
       the onset of diabetes mellitus.  In {\it Proceedings of the Symposium
       on Computer Applications and Medical Care} (pp. 261--265).  IEEE
       Computer Society Press.

       The diagnostic, binary-valued variable investigated is whether the
       patient shows signs of diabetes according to World Health Organization
       criteria (i.e., if the 2 hour post-load plasma glucose was at least
       200 mg/dl at any survey  examination or if found during routine medical
       care).   The population lives near Phoenix, Arizona, USA.

       Results: Their ADAP algorithm makes a real-valued prediction between
       0 and 1.  This was transformed into a binary decision using a cutoff of
       0.448.  Using 576 training instances, the sensitivity and specificity
       of their algorithm was 76% on the remaining 192 instances.

4. Relevant Information:
      Several constraints were placed on the selection of these instances from
      a larger database.  In particular, all patients here are females at
      least 21 years old of Pima Indian heritage.  ADAP is an adaptive learning
      routine that generates and executes digital analogs of perceptron-like
      devices.  It is a unique algorithm; see the paper for details.

5. Number of Instances: 768

6. Number of Attributes: 8 plus class

7. For Each Attribute: (all numeric-valued)
   1. Number of times pregnant
   2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
   3. Diastolic blood pressure (mm Hg)
   4. Triceps skin fold thickness (mm)
   5. 2-Hour serum insulin (mu U/ml)
   6. Body mass index (weight in kg/(height in m)^2)
   7. Diabetes pedigree function
   8. Age (years)
   9. Class variable (0 or 1)

8. Missing Attribute Values: Yes

9. Class Distribution: (class value 1 is interpreted as "tested positive for
   diabetes")

   Class Value  Number of instances
   0            500
   1            268

10. Brief statistical analysis:

    Attribute number:    Mean:   Standard Deviation:
    1.                     3.8     3.4
    2.                   120.9    32.0
    3.                    69.1    19.4
    4.                    20.5    16.0
    5.                    79.8   115.2
    6.                    32.0     7.9
    7.                     0.5     0.3
    8.                    33.2    11.8

In [7]:
features_names = ["pregnant", "glucose", "bp", "skin", "insulin", "bmi", "pedigree", "age", "flag"]

In [8]:
df_mod_diabets = pd.read_csv("pima-indians-diabetes.data", header=None, names=features_names)

In [11]:
#View dataset
df_mod_diabets.head()

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  flag
0         6      148  72    35        0  33.6     0.627   50     1
1         1       85  66    29        0  26.6     0.351   31     0
2         8      183  64     0        0  23.3     0.672   32     1
3         1       89  66    23       94  28.1     0.167   21     0
4         0      137  40    35      168  43.1     2.288   33     1

In [12]:
df_mod_diabets.shape

(768, 9)

In [13]:
features_select_df = ["pregnant", "insulin", "bmi", "age"]

In [14]:
#Creating featers object
x_features = df_mod_diabets[features_select_df]

In [15]:
y_target = df_mod_diabets["flag"]

In [16]:
x_features

     pregnant  insulin   bmi  age
0           6        0  33.6   50
1           1        0  26.6   31
2           8        0  23.3   32
3           1       94  28.1   21
4           0      168  43.1   33
..        ...      ...   ...  ...
763        10      180  32.9   63
764         2        0  36.8   27
765         5      112  26.2   30
766         1        0  30.1   47
767         1        0  30.4   23

[768 rows x 4 columns]

In [17]:
y_target

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: flag, Length: 768, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x_features, y_target, random_state=27)

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
log_reg = LogisticRegression()

In [22]:
log_reg.fit(x_train, y_train)

LogisticRegression()

In [23]:
#prediction user dataset
y_pred = log_reg.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
print(accuracy_score(y_test, y_pred))

0.7291666666666666

In [33]:
print("actuals " , y_test.values[0:30])
print("predict ", y_pred[0:30])

actuals  [0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0]
predict  [1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]